import { Alert, Medication, Supplier, Transaction, User, StockChangeRecord } from "@/types";
import { v4 as uuidv4 } from "uuid";

// Demo users
export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Admin User",
    email: "admin@pharmacy.com",
    role: "admin",
    createdAt: "2023-01-15T09:00:00Z",
  },
  {
    id: "u2",
    name: "Pharmacist User",
    email: "pharmacist@pharmacy.com",
    role: "pharmacist",
    createdAt: "2023-02-10T11:30:00Z",
  },
  {
    id: "u3",
    name: "Staff User",
    email: "staff@pharmacy.com",
    role: "staff",
    createdAt: "2023-03-05T14:15:00Z",
  },
];

// Demo suppliers
export const mockSuppliers: Supplier[] = [
  {
    id: "s1",
    name: "PharmaTech Solutions",
    email: "contact@pharmatech.com",
    phone: "+1 (555) 123-4567",
    address: "123 Medical Blvd, San Francisco, CA 94110",
    contactName: "John Smith",
    status: "active",
    createdAt: "2023-01-10T08:00:00Z",
    updatedAt: "2023-06-15T11:20:00Z",
  },
  {
    id: "s2",
    name: "MediSource Inc.",
    email: "info@medisource.com",
    phone: "+1 (555) 987-6543",
    address: "456 Health Ave, Chicago, IL 60607",
    contactName: "Sarah Jones",
    status: "active",
    createdAt: "2023-02-05T09:15:00Z",
    updatedAt: "2023-05-20T14:30:00Z",
  },
  {
    id: "s3",
    name: "Global Pharma Distributors",
    email: "sales@globalpharma.com",
    phone: "+1 (555) 789-0123",
    address: "789 Wellness Pkwy, Boston, MA 02210",
    contactName: "Michael Chen",
    status: "inactive",
    createdAt: "2023-03-15T10:45:00Z",
    updatedAt: "2023-04-10T16:00:00Z",
  },
];

// Demo medications
export const mockMedications: Medication[] = [
  {
    id: "m1",
    name: "Amoxicillin",
    description: "Broad-spectrum antibiotic",
    sku: "AMX-250",
    category: "Antibiotics",
    price: 7.50,
    costPrice: 3.20,
    stock: 150,
    expiryDate: "2024-12-31",
    manufacturer: "PharmaCorp",
    supplierId: "s1",
    createdAt: "2023-01-20T14:00:00Z",
    updatedAt: "2023-07-01T10:10:00Z",
  },
  {
    id: "m2",
    name: "Lisinopril",
    description: "ACE inhibitor for hypertension",
    sku: "LSN-10",
    category: "Cardiovascular",
    price: 5.00,
    costPrice: 1.80,
    stock: 200,
    expiryDate: "2025-01-15",
    manufacturer: "MediGenix",
    supplierId: "s2",
    createdAt: "2023-02-15T16:30:00Z",
    updatedAt: "2023-06-25T12:45:00Z",
  },
  {
    id: "m3",
    name: "Paracetamol",
    description: "Analgesic and antipyretic",
    sku: "PCM-500",
    category: "Analgesics",
    price: 3.00,
    costPrice: 1.00,
    stock: 300,
    expiryDate: "2024-11-30",
    manufacturer: "GlobalCare",
    supplierId: "s3",
    createdAt: "2023-03-10T11:00:00Z",
    updatedAt: "2023-05-10T15:20:00Z",
  },
  {
    id: "m4",
    name: "Atorvastatin",
    description: "Statin for lowering cholesterol",
    sku: "ATR-20",
    category: "Cardiovascular",
    price: 8.20,
    costPrice: 4.50,
    stock: 120,
    expiryDate: "2024-10-01",
    manufacturer: "PharmaCorp",
    supplierId: "s1",
    createdAt: "2023-04-05T09:30:00Z",
    updatedAt: "2023-07-15T13:00:00Z",
  },
  {
    id: "m5",
    name: "Metformin",
    description: "Biguanide for type 2 diabetes",
    sku: "MET-500",
    category: "Endocrine",
    price: 6.80,
    costPrice: 2.90,
    stock: 180,
    expiryDate: "2025-02-28",
    manufacturer: "MediGenix",
    supplierId: "s2",
    createdAt: "2023-05-01T13:45:00Z",
    updatedAt: "2023-06-01T16:40:00Z",
  },
];

// Demo transactions
export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    type: "sale",
    items: [
      { medicationId: "m1", medicationName: "Amoxicillin", quantity: 2, unitPrice: 7.50, subtotal: 15.00 },
      { medicationId: "m3", medicationName: "Paracetamol", quantity: 5, unitPrice: 3.00, subtotal: 15.00 },
    ],
    total: 30.00,
    customerName: "Alice Johnson",
    paymentMethod: "cash",
    status: "completed",
    notes: "Customer requested generic version",
    createdAt: "2023-07-20T10:00:00Z",
  },
  {
    id: "t2",
    type: "sale",
    items: [
      { medicationId: "m2", medicationName: "Lisinopril", quantity: 1, unitPrice: 5.00, subtotal: 5.00 },
    ],
    total: 5.00,
    customerName: "Bob Williams",
    paymentMethod: "card",
    status: "completed",
    notes: "Refill for chronic condition",
    createdAt: "2023-07-20T11:15:00Z",
  },
  {
    id: "t3",
    type: "purchase",
    items: [
      { medicationId: "m4", medicationName: "Atorvastatin", quantity: 50, unitPrice: 4.50, subtotal: 225.00 },
      { medicationId: "m5", medicationName: "Metformin", quantity: 30, unitPrice: 2.90, subtotal: 87.00 },
    ],
    total: 312.00,
    paymentMethod: "cash",
    status: "completed",
    notes: "Bulk order from PharmaCorp",
    createdAt: "2023-07-21T09:45:00Z",
  },
];

// Demo alerts
export const mockAlerts: Alert[] = [
  {
    id: "a1",
    type: "low-stock",
    medicationId: "m4",
    medicationName: "Atorvastatin",
    message: "Low stock: Atorvastatin is running low.",
    severity: "medium",
    isRead: false,
    createdAt: "2023-07-19T15:30:00Z",
  },
  {
    id: "a2",
    type: "expiry",
    medicationId: "m1",
    medicationName: "Amoxicillin",
    message: "Expiry: Amoxicillin is expiring soon.",
    severity: "high",
    isRead: false,
    createdAt: "2023-07-20T08:00:00Z",
  },
];

// Demo stock change records
export const mockStockChangeRecords: StockChangeRecord[] = [
  {
    id: uuidv4(),
    medicationId: "m1",
    medicationName: "Amoxicillin",
    previousStock: 100,
    newStock: 150,
    changeAmount: 50,
    changeType: "increase",
    reason: "Received new shipment",
    userId: "u2",
    userName: "Pharmacist User",
    timestamp: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    medicationId: "m2",
    medicationName: "Lisinopril",
    previousStock: 250,
    newStock: 200,
    changeAmount: 50,
    changeType: "decrease",
    reason: "Dispensed to patients",
    userId: "u3",
    userName: "Staff User",
    timestamp: new Date().toISOString(),
  },
];
